db-user: 'postgres'
db-password: 'password'
db-url: 'jdbc:postgresql://192.168.0.169:5432/movie_land'

spring:
  flyway:
    enabled: true
    locations: classpath:db.migration
    baseline-on-migrate: true

  datasource:
    username: ${db-user}
    password: ${db-password}
    url: ${db-url}
    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info