server:
  servlet:
    context-path: /api/v1

spring:
  flyway:
    enabled: true
    locations: classpath:db.migration #When it is removed flyway does not migrate
    baseline-on-migrate: true

  datasource:
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}/movie_land
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        order_updates: true

  profiles:
    active: dev-threads, prod-jpa

genre:
  refresh-cron: 0 0 */2 * * MON-SUN

ratings:
  flush-buffer: 0 */5 * * * MON-SUN
  refresh-avg-rating: 0 0 */1 * * MON-SUN

number:
  movies:
    random: 3

currency:
  url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?date=yyyyMMdd&json
  refresh-cron: 0 10 0 * * MON-SUN

encoder:
  strength: 11

token:
  time:
    unit: HOURS
  expiration:
    period: 2