server:
  servlet:
    context-path: /api/v1

spring:
  flyway:
    enabled: true
    locations: classpath:db.migration #When it is removed flyway does not migrate
    baseline-on-migrate: true

  datasource:
    username: ${USER_NAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}/movie_land
    driver-class-name: org.postgresql.Driver

genre:
  cache:
    cycle:
      hours: 4
number:
  movies:
    random: 3

currency:
  url: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange?json
  refresh-cron: 0 35 15 * * MON-SUN